# Problem 2 - Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

# initialize variables
evenvalued = 0
fib1 = 1
fib2 = 2

# repeat until all Fibonacci numbers less than 4000000 don't 
while fib2 < 4000000:

	# add fib2 to sum if it is even 
	if fib2 %2 == 0:
		evenvalued = evenvalued + fib2

	# increment variables to next 2 fibonacci numbers
	temp = fib1;
	fib1 = fib2;
	fib2 = fib1 + temp;

# output solution
print "The sum of all even-valued Fibonacci terms less than 4,000,000 is", evenvalued